### ISSUE TITLE
Problems with Usage notes

### ISSUE THREAD

**Issue by garyrob** [scull7/bs-sqlite#4]
The very first Usage note in the ReadMe doesn't compile in today's BuckleScript. Instead of `Js.true_`  it should just say `true`, the first `|>` should be `|.`, and there shouldn't be a paren at the end. Makes me wonder if the module as a whole will run, but I did get that first example working, at least. 

Is this project being maintained?

**Comment by garyrob** [comment]
No response in more than a month... is this project still alive? If not, maybe I should fork it?

**Comment by enieber** [comment]
@garyrob you make fork this project?

**Comment by scull7** [comment]
Sorry guys, I wasn't getting notifications. Seems that I am now.
